### ISSUE TITLE
Global stats?

### ISSUE THREAD

**Issue by xer0design** [bibaldo/MMM-COVID19#1]
Hey. How do you pull the total global stats? I’ve tried global, world, etc to no avail

**Comment by bibaldo** [comment]
Hi, it will be available in the next release later today

**Comment by bibaldo** [comment]
@xer0design updated!! Please pull the new modifications

**Comment by xer0design** [comment]
works great, thanks!

**Comment by hangorazvan** [comment]
not working, delete from my list

**Comment by bibaldo** [comment]
@hangorazvan what issue do you have with the module?

**Comment by hangorazvan** [comment]
> @hangorazvan what issue do you have with the module?

Now working, thx anyway.
