### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by hildwin** [bibaldo/MMM-COVID19#13]
Thanks for translating the module. Can I be helpful in any way to translate the names of the countries?

**Comment by bibaldo** [comment]
@hildwin 
if you like yes, but we will need translations for 'es' and 'de' too

**Comment by hildwin** [comment]
I've added the German names. I'll try to translate it via Wikipedia and Google Translate into Spanish, too. (If you trust me...)

**Comment by hildwin** [comment]
#23
