### ISSUE TITLE
Add number of "serious" cases

### ISSUE THREAD

**Issue by testdruif** [bibaldo/MMM-COVID19#14]
Hey Bibaldo,

Great plugin! I've been using it and adding some stats myself in the last weeks.
I see you've already added new deaths and new cases but there is one more stat the api provides.
The "serious" cases indicating the amount of people on intensive care. (great info to check against available icu beds of the country) It's only available on country level.

I've already added it to my code in order to show it, might be something you can add to the distro yourself? That way I don't have to update & redo my edit every time you update ;)

Much appreciated!

**Comment by testdruif** [comment]
Forked and created pull request with other changes

**Comment by bibaldo** [comment]
https://github.com/bibaldo/MMM-COVID19/pull/20 under review

**Comment by bibaldo** [comment]
done!
