### ISSUE TITLE
(Enhancement) US State by State basis?

### ISSUE THREAD

**Issue by river58** [bibaldo/MMM-COVID19#21]
Would be nice to be able to see both countries and specific US States!

**Comment by bibaldo** [comment]
yes, this could be done consuming `united_states_cases` endpoint from the API but it will require too much changes to the whole module just for one country (USA).
Feel free to open a PR and I will check it

**Comment by Plainbroke** [comment]
I was hoping you had already figured out how to do the USA States.  Take a look at MyCovid19, The
designer of that one module figured out how to get the States as an option... 
Maybe it would make it easier to do for you.   I don't know since coding is NOT in my wheelhouse.
