### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by PierreGode** [bibaldo/MMM-COVID19#24]
Hi! I have installed the module under modules and added to the magic mirror config.js
  {
    module: 'MMM-COVID19',
    config: {
      updateInterval: 30000,
      worldStats: true,
      //countries: [ "USA", "Italy", "Spain" ],
      headerRowClass: "small",
      rapidapiKey : "b82151b3d5msh55f3629c1a9****MY -rapidapi-KEY*********"
    }
  },

But the module is now showing in the mirror. I have several modules that are working.

also I con not see position config in your setup like: ( position: "top_left", )

I guess that I am missing something.

Best regards Pierre

**Comment by testdruif** [comment]
Hi Pierre,

I notice your api key includes the string "MY -rapidapi-KEY*****"
If that's in your live config it might be why no data is displayed

**Comment by PierreGode** [comment]
Hi no I hid it with purpose! I found the issue!  'MMM-COVID19', should be  "MMM-COVID19",
I made some changes to your readme file and sent an pull request

**Comment by PierreGode** [comment]
Solved fixing config.

my config is: ( api key is hidden ) replace  rapidapiKey: "get api from https://rapidapi.com/astsiatsko/api/coronavirus-monitor" with api key!
{
                module: "MMM-COVID19",
                header: "COVID19",
                position: "top_left",
                config:{
                        countries: ["USA", "Sweden", "China", "Spain", "Italy"],
                        delta: true,
                        worldStats: true,
                        updateInterval: 60 * 60 * 1000,
                        infoRowClass: "small",
                        headerRowClass: "small",
                        rapidapiKey: "get api from https://rapidapi.com/astsiatsko/api/coronavirus-monitor"
                }
        },

**Comment by PierreGode** [comment]
example image for the "Wecome page"
![image](https://user-images.githubusercontent.com/8579922/77920017-35215e80-729e-11ea-95e6-b5f58ed0463a.png)
