### ISSUE TITLE
change font size all

### ISSUE THREAD

**Issue by Jestergum** [bibaldo/MMM-COVID19#3]
High, thanks for the module, its great.
I happen to run into a font size issue where one module runs into another because of the large font.
The font of the header is changable, could the font of the numbers and countries be changeble too?

Thanks, 

I'd love to help out, tomorrow, time for bed.

**Comment by Jestergum** [comment]
I've been trying to figure it out with a custom.css file for general module config, but i'm a total noob with this.

**Comment by Jestergum** [comment]
Found a fix :D
in the .js file
after creation of wrapper : 
wrapper.style.fontSize = "25px";

**Comment by bibaldo** [comment]
@Jestergum I will change the font size of those things in a new release. I will add a class in order to have country name and numbers with one common size, and the header with another size

**Comment by bwente** [comment]
Unfortunately the columns are getting wider by the day. :(

The stats don't fit in my column layout anymore.

**Comment by bibaldo** [comment]
please, check new changes. You can now change the font-size for the data. Options are: `small`, `medium` or`big`
