### ISSUE TITLE
Any way to change UTC to EST in Config File?

### ISSUE THREAD

**Issue by tajakmal** [bibaldo/MMM-COVID19#31]
I was wondering if there is a way I can customize this to show data in Eastern Standard Time? Is it as simple as making a change in my config file?

Thanks!

**Comment by tajakmal** [comment]
Awesome @bibaldo - Thanks! looking forward to it.

**Comment by bibaldo** [comment]
@tajakmal it will take your current timezone

https://github.com/bibaldo/MMM-COVID19/pull/34

**Comment by tajakmal** [comment]
@bibaldo - Thanks!
