### ISSUE TITLE
Syntax error / Cases Per M

### ISSUE THREAD

**Issue by start-the-fire** [bibaldo/MMM-COVID19#35]
Hi,
I found a small syntax error towards the Cases Per M translation in the MMM-COVID19.js @ line 114

old : headerCasesPerMCell.innerHTML = this.translate('Cases per M')
new : headerCasesPerMCell.innerHTML = this.translate('Cases **P**er M')

Cheers & stay safe,
B

**Comment by bibaldo** [comment]
@start-the-fire thanks
I will commit it right away
