### ISSUE TITLE
Module is not visible 

### ISSUE THREAD

**Issue by hildwin** [bibaldo/MMM-COVID19#4]
After updating to the latest version the module isn't visible anymore. I already deleted the module completely and installed it again. 

Error in the log: 
> [15:35:03.466] [ERROR]  ERROR! Could not find main module js file for images

		{
			module: "MMM-COVID-19",
			header: "COVID-19",
			position: "top_left",
			config:{
				countries: ["Germany", "Austria", "Spain","Italy"],
				worldstats: true,
				updateInterval: 1000 * 60 * 60 * 6,
				headerRowClass: "small",
				rapidapiKey: "!secret"
			}
		},

> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

audited 220 packages in 10.423s
found 8 vulnerabilities (7 low, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details

> magicmirror@2.10.1 postinstall /home/pi/MagicMirror
> sh untrack-css.sh && sh installers/postinstall/postinstall.sh && npm run install-fonts

MagicMirror installation successful!

> magicmirror@2.10.1 install-fonts /home/pi/MagicMirror
> cd fonts && npm install

audited 1 package in 1.076s
found 0 vulnerabilities

audited 2766 packages in 56.338s

43 packages are looking for funding
  run `npm fund` for details

found 25 vulnerabilities (23 low, 2 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

Any ideas?

**Comment by hildwin** [comment]
Got it! The name of the modul changed from MMM-COVID-19 to MMM-COVID19!

**Comment by bibaldo** [comment]
@hildwin  nothing changed. It could be a typo from your side. Enjoy it!!
