### ISSUE TITLE
Not getting any data

### ISSUE THREAD

**Issue by stsanford** [bibaldo/MMM-COVID19#40]
I'm unsure of "You should first create an account on https://rapidapi.com/ and then go to https://rapidapi.com/astsiatsko/api/coronavirus-monitor, and use cases_by_country and worldstat endpoints" I did go and got an API key and added it, but I couldn't add cases_by_country AND worldstat that I can see to a single request. Sorry if I'm missing something...

Additionally, my config entry is:
{
			module: "MMM-COVID19",
			config: {
				position: "top_left",
				header: "COVID-19 Tracker",
				countries: ["USA"],
				worldStats: "true",
				lastUpdateInfo: "true",
				delta: "true",
				highlightCountry: "USA",
				headerRowClass: "small",
				infoRowClass: "small",
				updateInterval: "1500000",
				rapidapiKey: "37d6fa675ab4107...............CHANGED_FOR_POST"
			}
		},

**Comment by bibaldo** [comment]
Hi @stsanford , first of all, try to put `position: "top_left"` outside the module config. And let me know if that worked well

**Comment by stsanford** [comment]
Thank you, that looks to have done it!
