### ISSUE TITLE
how to add korea into config?

### ISSUE THREAD

**Issue by ghost** [bibaldo/MMM-COVID19#53]
```
{
		    module: "MMM-COVID19",
		    position: "top_left",
		    config: {
		      updateInterval: 300000,
		      worldStats: true,
		      delta: true,
		      lastUpdateInfo: true,
		      countries: [ "South-Korea", "China", "Italy", "Spain" ],
		      headerRowClass: "small",
		      rapidapiKey : "705fc0bb2fmsh4201f7c9bb9a89cp1a25a0jsna36534595cdb"
		    }
		},
```

this is what I have for config.js and it doesn't work. I've also tried 
"Korea"
"south_korea"

any help would be appreciated, thank you!

**Comment by springjjeon** [comment]
South Korea is set to "S. Korea".

**Comment by dntjd7701** [comment]
im trying to get info about South-Korea as like @kkongchi-maker  
so i chaged
countries: [ "S.Korea", "China", "Japan"]
but i can only see China, Japan
any help would be appreciated too, thank you!

**Comment by springjjeon** [comment]
hello.

You have to insert space between '.' and 'S'.

S."space"Korea

Have a good day!


2020년 9월 21일 (월) 오전 1:41, dntjd7701 <notifications@github.com>님이 작성:
