### ISSUE TITLE
Add refresh date

### ISSUE THREAD

**Issue by ezar** [bibaldo/MMM-COVID19#7]
Hi!
Magnific addon ;)
Can you add related refresh date info?

**Comment by bibaldo** [comment]
I thought about that. I will add it (via config option). Leave this issue open

**Comment by bibaldo** [comment]
@ezar I will add the data from the API
`"statistic_taken_at": "2020-03-20 01:53:05"`  UTC Time

**Comment by bibaldo** [comment]
@ezar check the last release. Enjoy!

**Comment by ezar** [comment]
Wow!! Fantastic ;)

**Comment by ezar** [comment]
Seems that this date is not the refresh data values. Is the request time. Is correct?

**Comment by herrschaftsseitn** [comment]
For me, the refresh date does not work, I get the message "statistic taken at Invalid date". Is there something i did configure wrong or can change in the configs? Thanks for your great work otherwise!
