### ISSUE TITLE
Configurable columns

### ISSUE THREAD

**Issue by chfshifter** [bibaldo/MMM-COVID19#9]
Excellent work! Are the columns configurable now? Looks like the JSON currently has some other interesting columns to show potentially (e.g. new cases/new deaths). Thanks!

**Comment by bibaldo** [comment]
I think is too much data. I wanted to keep only totals.
I will think about it and how it all fit if someone wants to see all info together (UI experience)

Cheers!!

**Comment by chfshifter** [comment]
@bibaldo  cool makes sense.
For a usage standpoint, unfortunately I've been staring at the dashboard for a day now and I often wonder if the totals have changed - often trying to recall from memory whether it was different and by how much! 

I'm new to MM but once I'm up to speed maybe I can contribute and think about the UI/UX.

**Comment by Plainbroke** [comment]
can you make a version of this to track the Flu in USA?

**Comment by bibaldo** [comment]
@Plainbroke I could. But not this time! Sorry!
